/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Devider: typeof import('./components/WindowDoor/Devider.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElementDemo: typeof import('./components/ElementDemo.vue')['default']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Glass: typeof import('./components/WindowDoor/Glass.vue')['default']
    Handle: typeof import('./components/WindowDoor/Handle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HorizontalMetric: typeof import('./components/WindowDoor/HorizontalMetric.vue')['default']
    IconAntDesignGithubFilled: typeof import('~icons/ant-design/github-filled')['default']
    IconCarbonUser: typeof import('~icons/carbon/user')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDemo: typeof import('./components/IconDemo.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTablerSettings: typeof import('~icons/tabler/settings')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Metrics: typeof import('./components/WindowDoor/Metrics.vue')['default']
    OpeningDirection: typeof import('./components/WindowDoor/OpeningDirection.vue')['default']
    RootFrame: typeof import('./components/WindowDoor/RootFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sash: typeof import('./components/WindowDoor/Sash.vue')['default']
    Section: typeof import('./components/WindowDoor/Section.vue')['default']
    SectionEdit: typeof import('./components/WindowDoor/SectionEdit.vue')['default']
    TestButton: typeof import('./components/TestButton.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VerticalMetric: typeof import('./components/WindowDoor/VerticalMetric.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
    WindowDoorApp: typeof import('./components/WindowDoor/WindowDoorApp.vue')['default']
  }
}
